apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-bank-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mobile-bank
      version: v1
  template:
    metadata:
      labels:
        app: mobile-bank
        version: v1
    spec:
      containers:
      - name: mobile-bank
        image: mobile-bank:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
