apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mobile-bank-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: mobile-bank.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mobile-bank-service
            port:
              number: 80
